name: Build Flet APK

on:
  push:
    branches: [ "main" ] # Спрацьовуватиме при кожному збереженні коду в гілку main
  workflow_dispatch: # Дозволяє запускати збірку вручну кнопкою

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-state: '3.11'

    - name: Set up Java (for Android SDK)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Flet and compiler
      run: |
        python -m pip install --upgrade pip
        pip install flet pyinstaller

    - name: Package app code
      run: flet pack main.py

    - name: Build Android APKyes 
      run: yes | flet build apk --module-name main

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: flet-android-app
        path: build/apk/app-release.apk
